#!/bin/bash

set -e

echo 'Installing udev rules to autoflash RP2040...'
cp 99-mch2022.rules /etc/udev/rules.d/
sed -i "s/{flashfolder_path}/$(pwd | sed -e 's/\//\\\//g')/g" /etc/udev/rules.d/99-mch2022.rules
udevadm control --reload && echo 'Udev rules installed & loaded'
